version: '3.8'
services:
  postgres:
    container_name: clinic-postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
  core:
    container_name: clinic-core
    build:
      context:
        ./clinic-core
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - admin
    env_file:
      - .env
  admin:
    container_name: clinic-admin
    ports:
      - "8085:8085"
    build:
      context:
        ./clinic-admin
    env_file:
      - .env