version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - clinic_net
  core:
    container_name: core
    build:
      context:
        ./clinic-core
    depends_on:
      - postgres
      - admin
    env_file:
      - .env
    networks:
      - clinic_net
  admin:
    container_name: admin
    build:
      context:
        ./clinic-admin
    env_file:
      - .env
    networks:
      - clinic_net
  frontend:
    container_name: frontend
    build:
      context:
        ./clinic-frontend
    ports:
      - "8080:8080"
    networks:
      - clinic_net
networks:
  clinic_net: