#Server
server:
  port: 8080
  servlet:
    context-path: /api
#Profile
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: core
  #Database
  datasource:
    password: ${POSTGRES_USER}
    username: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  #Liquibase
  liquibase:
    change-log: classpath:db.changelog/db-changelog-master.yaml
  #SpringBootAdmin
  boot:
    admin:
      client:
        username: ${CLINIC_ADMIN_USERNAME}
        password: ${CLINIC_ADMIN_PASSWORD}
        instance:
          metadata:
            user:
              name: dummyAdmin
              password: Usersecret!
#Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#JWT
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==