#Server
server:
  port: 8080
#Profile
spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: core
  #Database
  datasource:
    password: ${POSTGRES_USER}
    username: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
#Liquibase
  liquibase:
    change-log: classpath:db.changelog/db-changelog-master.yaml
#SpringBootAdmin
  boot:
    admin:
      client:
        username: ${CLINIC_ADMIN_USERNAME}
        password: ${CLINIC_ADMIN_PASSWORD}
        instance:
          metadata:
            user:
              name: dummyAdmin
              password: Usersecret!
#Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'